In [1]:
%cd \\sodfsv10\先端解析Ｇ\01_計算科学DB\080.チーム共有\90.AI開発T\解析プログラム

\\sodfsv10\先端解析Ｇ\01_計算科学DB\080.チーム共有\90.AI開発T\解析プログラム


In [2]:
from sklearn_expansion.experimental_design import kennard_stone

In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [4]:
X, y = load_iris(return_X_y=True)
X_ss = StandardScaler()
X_std = X_ss.fit_transform(X)

In [5]:
candidates = kennard_stone(X)

In [6]:
print(candidates)

[[6.2 2.8 4.8 1.8]
 [5.8 4.  1.2 0.2]
 [5.7 2.5 5.  2. ]
 [5.5 2.3 4.  1.3]
 [5.1 3.5 1.4 0.3]
 [7.3 2.9 6.3 1.8]
 [6.5 3.  5.8 2.2]
 [5.6 3.  4.5 1.5]
 [6.7 3.3 5.7 2.5]
 [6.9 3.1 5.1 2.3]]
